2.1/orm_shop/orm_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from main.views import cars_list_view, car_details_view, sales_by_car


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', cars_list_view, name='list'),
    path('cars/<int:car_id>/', car_details_view, name='details'),
    path('cars/<int:car_id>/sales/', sales_by_car, name='sales')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2.1/orm_shop/main/models.py
from django.db import models

class Client(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    phone_number = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name} {self.middle_name} {self.last_name}'


GEARBOX_CHOICES = (
    ('manual', 'Механика'),
    ('automatic', 'Автомат'),
    ('вариатор', 'CVT'),
    ('robot', 'Робот')
)

FUEL_TYPE_CHOICES = (
    ('gasoline', 'Бензин'),
    ('diesel', 'Дизель'),
    ('hybrid', 'Гибрид'),
    ('electro', 'Электро')
)

BODY_TYPE_CHOICES = (
    ('sedan', 'Седан'),
    ('hatchback', 'Хэтчбек'),
    ('SUV', 'Внедорожник'),
    ('wagon', 'Универсал'),
    ('minivan', 'Минивэн'),
    ('pickup', 'Пикап'),
    ('coupe', 'Купе'),
    ('cabrio', 'Кабриолет')
)


DRIVE_UNIT_CHOICES = (
    ('rear', 'Задний'),
    ('front', 'Передний'),
    ('full', 'Полный')
)


class Car(models.Model):
    # pass  # реализуйте модель
    # id = models.AutoField(primary_key=True
    model = models.CharField(max_length=60)
    year = models.SmallIntegerField()
    color = models.CharField(max_length=60)
    mileage = models.SmallIntegerField()
    volume = models.SmallIntegerField()
    body_type = models.CharField(max_length=20, choices=BODY_TYPE_CHOICES)
    drive_unit = models.CharField(max_length=20, choices=DRIVE_UNIT_CHOICES)
    gearbox = models.CharField(max_length=20, choices=GEARBOX_CHOICES)
    fuel_type = models.CharField(max_length=20, choices=FUEL_TYPE_CHOICES)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    image = models.ImageField(upload_to='Image')

    def __str__(self):
        return f'Автомобиль {self.model}, {self.year} года выпуска по цене {self.price}'


class Sale(models.Model):
    # pass  # реализуйте модель
    # id = models.AutoField(primary_key=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='client')
    car = models.OneToOneField(Car, on_delete=models.CASCADE, related_name='car')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return {self.client}

2.1/orm_shop/main/views.py
from django.http import Http404
from django.shortcuts import render

from main.models import Car
from main.models import Sale

def cars_list_view(request):
    # получите список авто
    cars = Car.objects.all()
    template_name = 'main/list.html'
    return render(request, template_name, {'cars': cars})  # передайте необходимый контекст


def car_details_view(request, car_id):
    # получите авто, если же его нет, выбросьте ошибку 404
    try:
        car = Car.objects.get(id=car_id)
        template_name = 'main/details.html'
        return render(request, template_name, {'car': car})
    except Car.DoesNotExist:
        raise Http404('Нет такой машины')
    #template_name = 'main/details.html'
    #return render(request, template_name, {})  # передайте необходимый контекст


def sales_by_car(request, car_id):
    try:
        # получите авто и его продажи
        car = Car.objects.get(id=car_id)
        sale = Sale.objects.get(id=car)
        template_name = 'main/sales.html'
        return render(request, template_name, {'sale': sale})  # передайте необходимый контекст
    except Car.DoesNotExist:
        raise Http404('Car not found')

2.1/orm_shop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>{% block title %}ORM Car showroom{% endblock title %}</title>

	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">
	{% block content %}
	{% endblock content %}

<!--	<footer id="footer">-->
<!--     <div class="container">-->
<!--     </div>-->
<!--	</footer>-->
	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/smoothscroll.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

2.1/orm_shop/templates/main/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ car.model }}{% endblock title %}
{% block content %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <div>
            <img src="{{ car.image.url }}" alt="" class="img-responsive wc-image">
          </div>
        </div>
        <div class="col-md-6 col-xs-12">
          <h2>{{ car.model }}, {{ car.year }}</h2>
          <p class="lead">Цена: <strong class="text-primary">{{ car.price | floatformat:"-2g" }} ₽</strong></p>
          <div class="row">
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Модель</span>
                <br>
                <strong>{{ car.model }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Год выпуска</span>
                <br>
                <strong>{{ car.year }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Коробка передач</span>
                <br>
                <strong>{{ car.get_gearbox_display }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Привод</span>
                <br>
                <strong>{{ car.get_drive_unit_display }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Пробег</span>
                <br>
                <strong>{{ car.mileage }} км</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Топливо</span>
                <br>
                <strong>{{ car.get_fuel_type_display }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Объем двигателя</span>
                <br>
                <strong>{{ car.volume }} л</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Кузов</span>
                <br>
                <strong>{{ car.get_body_type_display }}</strong>
              </p>
            </div>
            <div class="col-md-4 col-sm-6">
              <p>
                <span>Цвет</span>
                <br>
                <strong>{{ car.color }}</strong>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

2.1/orm_shop/templates/main/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Список авто{% endblock title %}

{% block content %}
	<section>
		<div class="container">
			<div class="text-center">
				<h1>Список автомобилей</h1>
				<br>
<!--				<div class="row">-->
<!--					<div class="col-lg-6 col-xs-12 col-lg-offset-3">-->
<!--						<div class="form">-->
<!--							<form action="{% url 'list' %}" method="get">-->
<!--								<div class="form-group">-->
<!--									<label class="control-label">Поиск авто</label>-->
<!--									<div class="input-group">-->
<!--										<input type="text" class="form-control" placeholder="Mercedes ..." name="q">-->
<!--										<span class="input-group-btn">-->
<!--											<button class="btn btn-default" type="submit">Найти!</button>-->
<!--										</span>-->
<!--									</div>-->
<!--								</div>-->
<!--							</form>-->
<!--						</div>-->
<!--					</div>-->
<!--				</div>-->
			</div>
		</div>
	</section>
	<section class="section-background">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-xs-12">
					<div class="row">
						{% for car in cars %}
							<div class="col-lg-4 col-md-4 col-sm-6">
							<div class="courses-thumb courses-thumb-secondary">
								<div class="courses-top">
									<div class="courses-image">
										<img src="{{ car.image.url }}" class="img-responsive" alt="">
									</div>
								</div>

								<div class="courses-detail">
									<h3><a href="car-details.html">{{ car.model }}</a></h3>
									<p class="lead">Цена: <strong>{{ car.price | floatformat:"-2g" }} ₽</strong></p>
									<p>{{ car.volume }} л. &nbsp;&nbsp;/&nbsp;&nbsp; {{ car.get_fuel_type_display }} &nbsp;&nbsp;/&nbsp;&nbsp; {{ car.year }} &nbsp;&nbsp;/&nbsp;&nbsp;
										{{ car.get_gearbox_display }}</p>
								</div>

								<div class="courses-info">
									<a href="{% url 'details' car.id %}" class="section-btn btn btn-primary btn-block">Подробнее</a>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock content %}

2.1/orm_shop/templates/main/sales.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ car.model }}{% endblock title %}
{% block content %}
  <div class="container">
			<div class="text-center">
				<h1>{{ car.model }} {{ car.year }}</h1>
				<br>
      </div>
  </div>
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Фамилия</th>
        <th scope="col">Имя</th>
        <th scope="col">Отчество</th>
        <th scope="col">Номер телефона</th>
        <th scope="col">Дата продажи</th>
      </tr>
    </thead>
    <tbody>
      {% for sale in sales %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ sale.client.last_name }}</td>
          <td>{{ sale.client.name }}</td>
          <td>{{ sale.client.middle_name }}</td>
          <td>{{ sale.client.phone_number }}</td>
          <td>{{ sale.created_at|date:"d/m/Y" }} {{ sale.created_at|time:"H:i" }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}